/**
 * Alias definitions for the "colors" trait set, grouped by canonical color key.
 * Each canonical key maps to an array of alias *labels*.
 */
export const COLOR_ALIASES: Record<string, string[]> = {
  red: ["Reddish", "Crimson", "Scarlet"],
  dark_red: ["Maroon", "Wine"],
  grayish_red: ["Brick red"],
  light_red_orange: ["Coral", "Salmon"],
  red_orange: ["Reddish orange", "Orange-red", "Vermilion"],
  grayish_red_orange: ["Tawny"],
  red_brown: [
    "Dark reddish orange",
    "Dark red-orange",
    "Rust-colored",
    "Rusty",
    "Rusty brown",
    "Rufous",
    "Ferruginous",
  ],
  pale_orange: ["Tan"],
  grayish_orange: ["Fulvous", "Ocher", "Ochre"],
  grayish_brown: [
    "Taupe",
    "Umber",
    "Dark grayish orange",
    "Brownish gray",
    "Fuscous",
  ],
  brown: ["Brownish", "Dark Orange"],
  light_yellow_orange: ["Buff", "Khaki"],
  yellow_orange: [
    "Yellowish orange",
    "Orangish yellow",
    "Amber",
    "Amber-colored",
    "Marigold",
  ],
  pale_yellow: ["Beige", "Cream-colored", "Straw-colored"],
  yellow: ["Yellowish", "Luteous"],
  olive_brown: ["Olive", "Olivaceous"],
  yellow_green: ["Chartreuse", "Yellowish green", "Greenish yellow", "Lime"],
  pale_green: ["Mint", "Minty"],
  blue_green: ["Cyan", "Bluish green", "Greenish blue"],
  grayish_blue_green: ["Viridian", "Turquoise"],
  blue: ["Bluish"],
  dark_blue: ["Navy", "Navy blue"],
  pale_purple: ["Lavender"],
  purple: ["Violet", "Purplish"],
  pale_red_purple: ["Mauve", "Lilac"],
  red_purple: ["Magenta", "Rose", "Fuchsia", "Reddish purple"],
  dark_red_purple: ["Burgundy", "Plum"],
  gray: ["Grey", "Grayish"],
  black: ["Jet black", "Fuliginous", "Blackish"],
  colorless: ["Hyaline", "Transparent"],
} as const;
