/**
 * Alias definitions for the "colors" trait set, keyed by canonical label.
 * Each canonical label maps to an array of alias labels.
 */
export const COLOR_ALIASES: Record<string, string[]> = {
  Red: ["Reddish", "Crimson", "Scarlet"],
  "Dark Red": ["Maroon", "Wine"],
  "Grayish Red": ["Brick red"],
  "Light Red-Orange": ["Coral", "Salmon"],
  "Red-Orange": ["Reddish orange", "Orange-red", "Vermilion"],
  "Grayish Red-Orange": ["Tawny"],
  "Red-Brown": [
    "Dark reddish orange",
    "Dark red-orange",
    "Rust-colored",
    "Rusty",
    "Rusty brown",
    "Rufous",
    "Ferruginous",
  ],
  "Pale Orange": ["Tan", "light brown"],
  "Grayish Orange": ["Fulvous", "Ocher", "Ochre"],
  "Grayish Brown": [
    "Taupe",
    "Umber",
    "Dark grayish orange",
    "Brownish gray",
    "Fuscous",
  ],
  Brown: ["Brownish", "Dark Orange"],
  "Light Yellow-Orange": ["Buff", "Khaki"],
  "Yellow-Orange": [
    "Yellowish orange",
    "Orangish yellow",
    "Amber",
    "Amber-colored",
    "Marigold",
  ],
  "Pale Yellow": ["Beige", "Cream-colored", "Creamy-white", "Straw-colored"],
  Yellow: ["Yellowish", "Luteous"],
  "Olive-Brown": ["Olive", "Olivaceous"],
  "Yellow-Green": ["Chartreuse", "Yellowish green", "Greenish yellow", "Lime"],
  "Pale Green": ["Mint", "Minty"],
  "Blue-Green": ["Cyan", "Bluish green", "Greenish blue"],
  "Grayish Blue-Green": ["Viridian", "Turquoise"],
  Blue: ["Bluish"],
  "Dark Blue": ["Navy", "Navy blue"],
  "Pale Purple": ["Lavender"],
  Purple: ["Violet", "Purplish"],
  "Pale Red-Purple": ["Mauve", "Lilac"],
  "Red-Purple": ["Magenta", "Rose", "Fuchsia", "Reddish purple"],
  "Dark Red-Purple": ["Burgundy", "Plum"],
  Gray: ["Grey", "Grayish"],
  Black: ["Jet black", "Fuliginous", "Blackish"],
  White: ["Whitish", "Off-white"],
  Colorless: ["Hyaline", "Transparent"],
} as const;
