/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSignupRouteImport } from './routes/_app/signup'
import { Route as AppLogoutRouteImport } from './routes/_app/logout'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppDonateRouteImport } from './routes/_app/donate'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AdminUsersRouteRouteImport } from './routes/admin/users/route'
import { Route as AppTaxaRouteRouteImport } from './routes/_app/taxa/route'
import { Route as AppGlossaryRouteRouteImport } from './routes/_app/glossary/route'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AppTaxaIndexRouteImport } from './routes/_app/taxa/index'
import { Route as AppGlossaryIndexRouteImport } from './routes/_app/glossary/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppTaxaNewRouteImport } from './routes/_app/taxa/new'
import { Route as AppTaxaDraftsRouteImport } from './routes/_app/taxa/drafts'
import { Route as AppUsersUsernameRouteRouteImport } from './routes/_app/users/$username/route'
import { Route as AppKeysBrowsingRouteRouteImport } from './routes/_app/keys/_browsing/route'
import { Route as AppGlossaryTraitsRouteRouteImport } from './routes/_app/glossary/traits/route'
import { Route as AppGlossaryGroupsRouteRouteImport } from './routes/_app/glossary/groups/route'
import { Route as AppGlossaryCharactersRouteRouteImport } from './routes/_app/glossary/characters/route'
import { Route as AppUsersUsernameIndexRouteImport } from './routes/_app/users/$username/index'
import { Route as AppTaxaIdIndexRouteImport } from './routes/_app/taxa/$id/index'
import { Route as AppKeysCreateIndexRouteImport } from './routes/_app/keys/create/index'
import { Route as AppKeysBrowsingIndexRouteImport } from './routes/_app/keys/_browsing/index'
import { Route as AppKeysKeyIdIndexRouteImport } from './routes/_app/keys/$keyId/index'
import { Route as AppGlossaryTraitsIndexRouteImport } from './routes/_app/glossary/traits/index'
import { Route as AppGlossaryGroupsIndexRouteImport } from './routes/_app/glossary/groups/index'
import { Route as AppGlossaryCharactersIndexRouteImport } from './routes/_app/glossary/characters/index'
import { Route as AppUsersUsernameEditRouteImport } from './routes/_app/users/$username/edit'
import { Route as AppGlossaryGroupsGroupIdRouteImport } from './routes/_app/glossary/groups/$groupId'
import { Route as AppGlossaryCharactersCharacterIdRouteImport } from './routes/_app/glossary/characters/$characterId'
import { Route as AppTaxaIdEditRouteRouteImport } from './routes/_app/taxa/$id/edit/route'
import { Route as AppTaxaIdEditIndexRouteImport } from './routes/_app/taxa/$id/edit/index'
import { Route as AppGlossaryTraitsSetIdIndexRouteImport } from './routes/_app/glossary/traits/$setId/index'

const AppKeysRouteImport = createFileRoute('/_app/keys')()

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppKeysRoute = AppKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSignupRoute = AppSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLogoutRoute = AppLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDonateRoute = AppDonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminUsersRouteRoute = AdminUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppTaxaRouteRoute = AppTaxaRouteRouteImport.update({
  id: '/taxa',
  path: '/taxa',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGlossaryRouteRoute = AppGlossaryRouteRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRouteRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTaxaIndexRoute = AppTaxaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTaxaRouteRoute,
} as any)
const AppGlossaryIndexRoute = AppGlossaryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGlossaryRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTaxaNewRoute = AppTaxaNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTaxaRouteRoute,
} as any)
const AppTaxaDraftsRoute = AppTaxaDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AppTaxaRouteRoute,
} as any)
const AppUsersUsernameRouteRoute = AppUsersUsernameRouteRouteImport.update({
  id: '/users/$username',
  path: '/users/$username',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKeysBrowsingRouteRoute = AppKeysBrowsingRouteRouteImport.update({
  id: '/_browsing',
  getParentRoute: () => AppKeysRoute,
} as any)
const AppGlossaryTraitsRouteRoute = AppGlossaryTraitsRouteRouteImport.update({
  id: '/traits',
  path: '/traits',
  getParentRoute: () => AppGlossaryRouteRoute,
} as any)
const AppGlossaryGroupsRouteRoute = AppGlossaryGroupsRouteRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppGlossaryRouteRoute,
} as any)
const AppGlossaryCharactersRouteRoute =
  AppGlossaryCharactersRouteRouteImport.update({
    id: '/characters',
    path: '/characters',
    getParentRoute: () => AppGlossaryRouteRoute,
  } as any)
const AppUsersUsernameIndexRoute = AppUsersUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUsersUsernameRouteRoute,
} as any)
const AppTaxaIdIndexRoute = AppTaxaIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => AppTaxaRouteRoute,
} as any)
const AppKeysCreateIndexRoute = AppKeysCreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => AppKeysRoute,
} as any)
const AppKeysBrowsingIndexRoute = AppKeysBrowsingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppKeysBrowsingRouteRoute,
} as any)
const AppKeysKeyIdIndexRoute = AppKeysKeyIdIndexRouteImport.update({
  id: '/$keyId/',
  path: '/$keyId/',
  getParentRoute: () => AppKeysRoute,
} as any)
const AppGlossaryTraitsIndexRoute = AppGlossaryTraitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGlossaryTraitsRouteRoute,
} as any)
const AppGlossaryGroupsIndexRoute = AppGlossaryGroupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppGlossaryGroupsRouteRoute,
} as any)
const AppGlossaryCharactersIndexRoute =
  AppGlossaryCharactersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppGlossaryCharactersRouteRoute,
  } as any)
const AppUsersUsernameEditRoute = AppUsersUsernameEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppUsersUsernameRouteRoute,
} as any)
const AppGlossaryGroupsGroupIdRoute =
  AppGlossaryGroupsGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => AppGlossaryGroupsRouteRoute,
  } as any)
const AppGlossaryCharactersCharacterIdRoute =
  AppGlossaryCharactersCharacterIdRouteImport.update({
    id: '/$characterId',
    path: '/$characterId',
    getParentRoute: () => AppGlossaryCharactersRouteRoute,
  } as any)
const AppTaxaIdEditRouteRoute = AppTaxaIdEditRouteRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AppTaxaRouteRoute,
} as any)
const AppTaxaIdEditIndexRoute = AppTaxaIdEditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTaxaIdEditRouteRoute,
} as any)
const AppGlossaryTraitsSetIdIndexRoute =
  AppGlossaryTraitsSetIdIndexRouteImport.update({
    id: '/$setId/',
    path: '/$setId/',
    getParentRoute: () => AppGlossaryTraitsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/glossary': typeof AppGlossaryRouteRouteWithChildren
  '/taxa': typeof AppTaxaRouteRouteWithChildren
  '/admin/users': typeof AdminUsersRouteRouteWithChildren
  '/about': typeof AppAboutRoute
  '/donate': typeof AppDonateRoute
  '/login': typeof AppLoginRoute
  '/logout': typeof AppLogoutRoute
  '/signup': typeof AppSignupRoute
  '/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/glossary/characters': typeof AppGlossaryCharactersRouteRouteWithChildren
  '/glossary/groups': typeof AppGlossaryGroupsRouteRouteWithChildren
  '/glossary/traits': typeof AppGlossaryTraitsRouteRouteWithChildren
  '/keys': typeof AppKeysBrowsingRouteRouteWithChildren
  '/users/$username': typeof AppUsersUsernameRouteRouteWithChildren
  '/taxa/drafts': typeof AppTaxaDraftsRoute
  '/taxa/new': typeof AppTaxaNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/glossary/': typeof AppGlossaryIndexRoute
  '/taxa/': typeof AppTaxaIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/taxa/$id/edit': typeof AppTaxaIdEditRouteRouteWithChildren
  '/glossary/characters/$characterId': typeof AppGlossaryCharactersCharacterIdRoute
  '/glossary/groups/$groupId': typeof AppGlossaryGroupsGroupIdRoute
  '/users/$username/edit': typeof AppUsersUsernameEditRoute
  '/glossary/characters/': typeof AppGlossaryCharactersIndexRoute
  '/glossary/groups/': typeof AppGlossaryGroupsIndexRoute
  '/glossary/traits/': typeof AppGlossaryTraitsIndexRoute
  '/keys/$keyId': typeof AppKeysKeyIdIndexRoute
  '/keys/': typeof AppKeysBrowsingIndexRoute
  '/keys/create': typeof AppKeysCreateIndexRoute
  '/taxa/$id': typeof AppTaxaIdIndexRoute
  '/users/$username/': typeof AppUsersUsernameIndexRoute
  '/glossary/traits/$setId': typeof AppGlossaryTraitsSetIdIndexRoute
  '/taxa/$id/edit/': typeof AppTaxaIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AppAboutRoute
  '/donate': typeof AppDonateRoute
  '/login': typeof AppLoginRoute
  '/logout': typeof AppLogoutRoute
  '/signup': typeof AppSignupRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/keys': typeof AppKeysBrowsingIndexRoute
  '/taxa/drafts': typeof AppTaxaDraftsRoute
  '/taxa/new': typeof AppTaxaNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/glossary': typeof AppGlossaryIndexRoute
  '/taxa': typeof AppTaxaIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/glossary/characters/$characterId': typeof AppGlossaryCharactersCharacterIdRoute
  '/glossary/groups/$groupId': typeof AppGlossaryGroupsGroupIdRoute
  '/users/$username/edit': typeof AppUsersUsernameEditRoute
  '/glossary/characters': typeof AppGlossaryCharactersIndexRoute
  '/glossary/groups': typeof AppGlossaryGroupsIndexRoute
  '/glossary/traits': typeof AppGlossaryTraitsIndexRoute
  '/keys/$keyId': typeof AppKeysKeyIdIndexRoute
  '/keys/create': typeof AppKeysCreateIndexRoute
  '/taxa/$id': typeof AppTaxaIdIndexRoute
  '/users/$username': typeof AppUsersUsernameIndexRoute
  '/glossary/traits/$setId': typeof AppGlossaryTraitsSetIdIndexRoute
  '/taxa/$id/edit': typeof AppTaxaIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_app/glossary': typeof AppGlossaryRouteRouteWithChildren
  '/_app/taxa': typeof AppTaxaRouteRouteWithChildren
  '/admin/users': typeof AdminUsersRouteRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/donate': typeof AppDonateRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/logout': typeof AppLogoutRoute
  '/_app/signup': typeof AppSignupRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/glossary/characters': typeof AppGlossaryCharactersRouteRouteWithChildren
  '/_app/glossary/groups': typeof AppGlossaryGroupsRouteRouteWithChildren
  '/_app/glossary/traits': typeof AppGlossaryTraitsRouteRouteWithChildren
  '/_app/keys': typeof AppKeysRouteWithChildren
  '/_app/keys/_browsing': typeof AppKeysBrowsingRouteRouteWithChildren
  '/_app/users/$username': typeof AppUsersUsernameRouteRouteWithChildren
  '/_app/taxa/drafts': typeof AppTaxaDraftsRoute
  '/_app/taxa/new': typeof AppTaxaNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/glossary/': typeof AppGlossaryIndexRoute
  '/_app/taxa/': typeof AppTaxaIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/_app/taxa/$id/edit': typeof AppTaxaIdEditRouteRouteWithChildren
  '/_app/glossary/characters/$characterId': typeof AppGlossaryCharactersCharacterIdRoute
  '/_app/glossary/groups/$groupId': typeof AppGlossaryGroupsGroupIdRoute
  '/_app/users/$username/edit': typeof AppUsersUsernameEditRoute
  '/_app/glossary/characters/': typeof AppGlossaryCharactersIndexRoute
  '/_app/glossary/groups/': typeof AppGlossaryGroupsIndexRoute
  '/_app/glossary/traits/': typeof AppGlossaryTraitsIndexRoute
  '/_app/keys/$keyId/': typeof AppKeysKeyIdIndexRoute
  '/_app/keys/_browsing/': typeof AppKeysBrowsingIndexRoute
  '/_app/keys/create/': typeof AppKeysCreateIndexRoute
  '/_app/taxa/$id/': typeof AppTaxaIdIndexRoute
  '/_app/users/$username/': typeof AppUsersUsernameIndexRoute
  '/_app/glossary/traits/$setId/': typeof AppGlossaryTraitsSetIdIndexRoute
  '/_app/taxa/$id/edit/': typeof AppTaxaIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/glossary'
    | '/taxa'
    | '/admin/users'
    | '/about'
    | '/donate'
    | '/login'
    | '/logout'
    | '/signup'
    | '/'
    | '/admin/'
    | '/glossary/characters'
    | '/glossary/groups'
    | '/glossary/traits'
    | '/keys'
    | '/users/$username'
    | '/taxa/drafts'
    | '/taxa/new'
    | '/api/auth/$'
    | '/glossary/'
    | '/taxa/'
    | '/users'
    | '/admin/users/'
    | '/taxa/$id/edit'
    | '/glossary/characters/$characterId'
    | '/glossary/groups/$groupId'
    | '/users/$username/edit'
    | '/glossary/characters/'
    | '/glossary/groups/'
    | '/glossary/traits/'
    | '/keys/$keyId'
    | '/keys/'
    | '/keys/create'
    | '/taxa/$id'
    | '/users/$username/'
    | '/glossary/traits/$setId'
    | '/taxa/$id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/donate'
    | '/login'
    | '/logout'
    | '/signup'
    | '/'
    | '/admin'
    | '/keys'
    | '/taxa/drafts'
    | '/taxa/new'
    | '/api/auth/$'
    | '/glossary'
    | '/taxa'
    | '/users'
    | '/admin/users'
    | '/glossary/characters/$characterId'
    | '/glossary/groups/$groupId'
    | '/users/$username/edit'
    | '/glossary/characters'
    | '/glossary/groups'
    | '/glossary/traits'
    | '/keys/$keyId'
    | '/keys/create'
    | '/taxa/$id'
    | '/users/$username'
    | '/glossary/traits/$setId'
    | '/taxa/$id/edit'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/_app/glossary'
    | '/_app/taxa'
    | '/admin/users'
    | '/_app/about'
    | '/_app/donate'
    | '/_app/login'
    | '/_app/logout'
    | '/_app/signup'
    | '/_app/'
    | '/admin/'
    | '/_app/glossary/characters'
    | '/_app/glossary/groups'
    | '/_app/glossary/traits'
    | '/_app/keys'
    | '/_app/keys/_browsing'
    | '/_app/users/$username'
    | '/_app/taxa/drafts'
    | '/_app/taxa/new'
    | '/api/auth/$'
    | '/_app/glossary/'
    | '/_app/taxa/'
    | '/_app/users/'
    | '/admin/users/'
    | '/_app/taxa/$id/edit'
    | '/_app/glossary/characters/$characterId'
    | '/_app/glossary/groups/$groupId'
    | '/_app/users/$username/edit'
    | '/_app/glossary/characters/'
    | '/_app/glossary/groups/'
    | '/_app/glossary/traits/'
    | '/_app/keys/$keyId/'
    | '/_app/keys/_browsing/'
    | '/_app/keys/create/'
    | '/_app/taxa/$id/'
    | '/_app/users/$username/'
    | '/_app/glossary/traits/$setId/'
    | '/_app/taxa/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/keys': {
      id: '/_app/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AppKeysRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/signup': {
      id: '/_app/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AppSignupRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/logout': {
      id: '/_app/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof AppLogoutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/donate': {
      id: '/_app/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof AppDonateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_app/taxa': {
      id: '/_app/taxa'
      path: '/taxa'
      fullPath: '/taxa'
      preLoaderRoute: typeof AppTaxaRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/glossary': {
      id: '/_app/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof AppGlossaryRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRouteRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/taxa/': {
      id: '/_app/taxa/'
      path: '/'
      fullPath: '/taxa/'
      preLoaderRoute: typeof AppTaxaIndexRouteImport
      parentRoute: typeof AppTaxaRouteRoute
    }
    '/_app/glossary/': {
      id: '/_app/glossary/'
      path: '/'
      fullPath: '/glossary/'
      preLoaderRoute: typeof AppGlossaryIndexRouteImport
      parentRoute: typeof AppGlossaryRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/taxa/new': {
      id: '/_app/taxa/new'
      path: '/new'
      fullPath: '/taxa/new'
      preLoaderRoute: typeof AppTaxaNewRouteImport
      parentRoute: typeof AppTaxaRouteRoute
    }
    '/_app/taxa/drafts': {
      id: '/_app/taxa/drafts'
      path: '/drafts'
      fullPath: '/taxa/drafts'
      preLoaderRoute: typeof AppTaxaDraftsRouteImport
      parentRoute: typeof AppTaxaRouteRoute
    }
    '/_app/users/$username': {
      id: '/_app/users/$username'
      path: '/users/$username'
      fullPath: '/users/$username'
      preLoaderRoute: typeof AppUsersUsernameRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/keys/_browsing': {
      id: '/_app/keys/_browsing'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AppKeysBrowsingRouteRouteImport
      parentRoute: typeof AppKeysRoute
    }
    '/_app/glossary/traits': {
      id: '/_app/glossary/traits'
      path: '/traits'
      fullPath: '/glossary/traits'
      preLoaderRoute: typeof AppGlossaryTraitsRouteRouteImport
      parentRoute: typeof AppGlossaryRouteRoute
    }
    '/_app/glossary/groups': {
      id: '/_app/glossary/groups'
      path: '/groups'
      fullPath: '/glossary/groups'
      preLoaderRoute: typeof AppGlossaryGroupsRouteRouteImport
      parentRoute: typeof AppGlossaryRouteRoute
    }
    '/_app/glossary/characters': {
      id: '/_app/glossary/characters'
      path: '/characters'
      fullPath: '/glossary/characters'
      preLoaderRoute: typeof AppGlossaryCharactersRouteRouteImport
      parentRoute: typeof AppGlossaryRouteRoute
    }
    '/_app/users/$username/': {
      id: '/_app/users/$username/'
      path: '/'
      fullPath: '/users/$username/'
      preLoaderRoute: typeof AppUsersUsernameIndexRouteImport
      parentRoute: typeof AppUsersUsernameRouteRoute
    }
    '/_app/taxa/$id/': {
      id: '/_app/taxa/$id/'
      path: '/$id'
      fullPath: '/taxa/$id'
      preLoaderRoute: typeof AppTaxaIdIndexRouteImport
      parentRoute: typeof AppTaxaRouteRoute
    }
    '/_app/keys/create/': {
      id: '/_app/keys/create/'
      path: '/create'
      fullPath: '/keys/create'
      preLoaderRoute: typeof AppKeysCreateIndexRouteImport
      parentRoute: typeof AppKeysRoute
    }
    '/_app/keys/_browsing/': {
      id: '/_app/keys/_browsing/'
      path: '/'
      fullPath: '/keys/'
      preLoaderRoute: typeof AppKeysBrowsingIndexRouteImport
      parentRoute: typeof AppKeysBrowsingRouteRoute
    }
    '/_app/keys/$keyId/': {
      id: '/_app/keys/$keyId/'
      path: '/$keyId'
      fullPath: '/keys/$keyId'
      preLoaderRoute: typeof AppKeysKeyIdIndexRouteImport
      parentRoute: typeof AppKeysRoute
    }
    '/_app/glossary/traits/': {
      id: '/_app/glossary/traits/'
      path: '/'
      fullPath: '/glossary/traits/'
      preLoaderRoute: typeof AppGlossaryTraitsIndexRouteImport
      parentRoute: typeof AppGlossaryTraitsRouteRoute
    }
    '/_app/glossary/groups/': {
      id: '/_app/glossary/groups/'
      path: '/'
      fullPath: '/glossary/groups/'
      preLoaderRoute: typeof AppGlossaryGroupsIndexRouteImport
      parentRoute: typeof AppGlossaryGroupsRouteRoute
    }
    '/_app/glossary/characters/': {
      id: '/_app/glossary/characters/'
      path: '/'
      fullPath: '/glossary/characters/'
      preLoaderRoute: typeof AppGlossaryCharactersIndexRouteImport
      parentRoute: typeof AppGlossaryCharactersRouteRoute
    }
    '/_app/users/$username/edit': {
      id: '/_app/users/$username/edit'
      path: '/edit'
      fullPath: '/users/$username/edit'
      preLoaderRoute: typeof AppUsersUsernameEditRouteImport
      parentRoute: typeof AppUsersUsernameRouteRoute
    }
    '/_app/glossary/groups/$groupId': {
      id: '/_app/glossary/groups/$groupId'
      path: '/$groupId'
      fullPath: '/glossary/groups/$groupId'
      preLoaderRoute: typeof AppGlossaryGroupsGroupIdRouteImport
      parentRoute: typeof AppGlossaryGroupsRouteRoute
    }
    '/_app/glossary/characters/$characterId': {
      id: '/_app/glossary/characters/$characterId'
      path: '/$characterId'
      fullPath: '/glossary/characters/$characterId'
      preLoaderRoute: typeof AppGlossaryCharactersCharacterIdRouteImport
      parentRoute: typeof AppGlossaryCharactersRouteRoute
    }
    '/_app/taxa/$id/edit': {
      id: '/_app/taxa/$id/edit'
      path: '/$id/edit'
      fullPath: '/taxa/$id/edit'
      preLoaderRoute: typeof AppTaxaIdEditRouteRouteImport
      parentRoute: typeof AppTaxaRouteRoute
    }
    '/_app/taxa/$id/edit/': {
      id: '/_app/taxa/$id/edit/'
      path: '/'
      fullPath: '/taxa/$id/edit/'
      preLoaderRoute: typeof AppTaxaIdEditIndexRouteImport
      parentRoute: typeof AppTaxaIdEditRouteRoute
    }
    '/_app/glossary/traits/$setId/': {
      id: '/_app/glossary/traits/$setId/'
      path: '/$setId'
      fullPath: '/glossary/traits/$setId'
      preLoaderRoute: typeof AppGlossaryTraitsSetIdIndexRouteImport
      parentRoute: typeof AppGlossaryTraitsRouteRoute
    }
  }
}

interface AppGlossaryCharactersRouteRouteChildren {
  AppGlossaryCharactersCharacterIdRoute: typeof AppGlossaryCharactersCharacterIdRoute
  AppGlossaryCharactersIndexRoute: typeof AppGlossaryCharactersIndexRoute
}

const AppGlossaryCharactersRouteRouteChildren: AppGlossaryCharactersRouteRouteChildren =
  {
    AppGlossaryCharactersCharacterIdRoute:
      AppGlossaryCharactersCharacterIdRoute,
    AppGlossaryCharactersIndexRoute: AppGlossaryCharactersIndexRoute,
  }

const AppGlossaryCharactersRouteRouteWithChildren =
  AppGlossaryCharactersRouteRoute._addFileChildren(
    AppGlossaryCharactersRouteRouteChildren,
  )

interface AppGlossaryGroupsRouteRouteChildren {
  AppGlossaryGroupsGroupIdRoute: typeof AppGlossaryGroupsGroupIdRoute
  AppGlossaryGroupsIndexRoute: typeof AppGlossaryGroupsIndexRoute
}

const AppGlossaryGroupsRouteRouteChildren: AppGlossaryGroupsRouteRouteChildren =
  {
    AppGlossaryGroupsGroupIdRoute: AppGlossaryGroupsGroupIdRoute,
    AppGlossaryGroupsIndexRoute: AppGlossaryGroupsIndexRoute,
  }

const AppGlossaryGroupsRouteRouteWithChildren =
  AppGlossaryGroupsRouteRoute._addFileChildren(
    AppGlossaryGroupsRouteRouteChildren,
  )

interface AppGlossaryTraitsRouteRouteChildren {
  AppGlossaryTraitsIndexRoute: typeof AppGlossaryTraitsIndexRoute
  AppGlossaryTraitsSetIdIndexRoute: typeof AppGlossaryTraitsSetIdIndexRoute
}

const AppGlossaryTraitsRouteRouteChildren: AppGlossaryTraitsRouteRouteChildren =
  {
    AppGlossaryTraitsIndexRoute: AppGlossaryTraitsIndexRoute,
    AppGlossaryTraitsSetIdIndexRoute: AppGlossaryTraitsSetIdIndexRoute,
  }

const AppGlossaryTraitsRouteRouteWithChildren =
  AppGlossaryTraitsRouteRoute._addFileChildren(
    AppGlossaryTraitsRouteRouteChildren,
  )

interface AppGlossaryRouteRouteChildren {
  AppGlossaryCharactersRouteRoute: typeof AppGlossaryCharactersRouteRouteWithChildren
  AppGlossaryGroupsRouteRoute: typeof AppGlossaryGroupsRouteRouteWithChildren
  AppGlossaryTraitsRouteRoute: typeof AppGlossaryTraitsRouteRouteWithChildren
  AppGlossaryIndexRoute: typeof AppGlossaryIndexRoute
}

const AppGlossaryRouteRouteChildren: AppGlossaryRouteRouteChildren = {
  AppGlossaryCharactersRouteRoute: AppGlossaryCharactersRouteRouteWithChildren,
  AppGlossaryGroupsRouteRoute: AppGlossaryGroupsRouteRouteWithChildren,
  AppGlossaryTraitsRouteRoute: AppGlossaryTraitsRouteRouteWithChildren,
  AppGlossaryIndexRoute: AppGlossaryIndexRoute,
}

const AppGlossaryRouteRouteWithChildren =
  AppGlossaryRouteRoute._addFileChildren(AppGlossaryRouteRouteChildren)

interface AppTaxaIdEditRouteRouteChildren {
  AppTaxaIdEditIndexRoute: typeof AppTaxaIdEditIndexRoute
}

const AppTaxaIdEditRouteRouteChildren: AppTaxaIdEditRouteRouteChildren = {
  AppTaxaIdEditIndexRoute: AppTaxaIdEditIndexRoute,
}

const AppTaxaIdEditRouteRouteWithChildren =
  AppTaxaIdEditRouteRoute._addFileChildren(AppTaxaIdEditRouteRouteChildren)

interface AppTaxaRouteRouteChildren {
  AppTaxaDraftsRoute: typeof AppTaxaDraftsRoute
  AppTaxaNewRoute: typeof AppTaxaNewRoute
  AppTaxaIndexRoute: typeof AppTaxaIndexRoute
  AppTaxaIdEditRouteRoute: typeof AppTaxaIdEditRouteRouteWithChildren
  AppTaxaIdIndexRoute: typeof AppTaxaIdIndexRoute
}

const AppTaxaRouteRouteChildren: AppTaxaRouteRouteChildren = {
  AppTaxaDraftsRoute: AppTaxaDraftsRoute,
  AppTaxaNewRoute: AppTaxaNewRoute,
  AppTaxaIndexRoute: AppTaxaIndexRoute,
  AppTaxaIdEditRouteRoute: AppTaxaIdEditRouteRouteWithChildren,
  AppTaxaIdIndexRoute: AppTaxaIdIndexRoute,
}

const AppTaxaRouteRouteWithChildren = AppTaxaRouteRoute._addFileChildren(
  AppTaxaRouteRouteChildren,
)

interface AppKeysBrowsingRouteRouteChildren {
  AppKeysBrowsingIndexRoute: typeof AppKeysBrowsingIndexRoute
}

const AppKeysBrowsingRouteRouteChildren: AppKeysBrowsingRouteRouteChildren = {
  AppKeysBrowsingIndexRoute: AppKeysBrowsingIndexRoute,
}

const AppKeysBrowsingRouteRouteWithChildren =
  AppKeysBrowsingRouteRoute._addFileChildren(AppKeysBrowsingRouteRouteChildren)

interface AppKeysRouteChildren {
  AppKeysBrowsingRouteRoute: typeof AppKeysBrowsingRouteRouteWithChildren
  AppKeysKeyIdIndexRoute: typeof AppKeysKeyIdIndexRoute
  AppKeysCreateIndexRoute: typeof AppKeysCreateIndexRoute
}

const AppKeysRouteChildren: AppKeysRouteChildren = {
  AppKeysBrowsingRouteRoute: AppKeysBrowsingRouteRouteWithChildren,
  AppKeysKeyIdIndexRoute: AppKeysKeyIdIndexRoute,
  AppKeysCreateIndexRoute: AppKeysCreateIndexRoute,
}

const AppKeysRouteWithChildren =
  AppKeysRoute._addFileChildren(AppKeysRouteChildren)

interface AppUsersUsernameRouteRouteChildren {
  AppUsersUsernameEditRoute: typeof AppUsersUsernameEditRoute
  AppUsersUsernameIndexRoute: typeof AppUsersUsernameIndexRoute
}

const AppUsersUsernameRouteRouteChildren: AppUsersUsernameRouteRouteChildren = {
  AppUsersUsernameEditRoute: AppUsersUsernameEditRoute,
  AppUsersUsernameIndexRoute: AppUsersUsernameIndexRoute,
}

const AppUsersUsernameRouteRouteWithChildren =
  AppUsersUsernameRouteRoute._addFileChildren(
    AppUsersUsernameRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppGlossaryRouteRoute: typeof AppGlossaryRouteRouteWithChildren
  AppTaxaRouteRoute: typeof AppTaxaRouteRouteWithChildren
  AppAboutRoute: typeof AppAboutRoute
  AppDonateRoute: typeof AppDonateRoute
  AppLoginRoute: typeof AppLoginRoute
  AppLogoutRoute: typeof AppLogoutRoute
  AppSignupRoute: typeof AppSignupRoute
  AppIndexRoute: typeof AppIndexRoute
  AppKeysRoute: typeof AppKeysRouteWithChildren
  AppUsersUsernameRouteRoute: typeof AppUsersUsernameRouteRouteWithChildren
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppGlossaryRouteRoute: AppGlossaryRouteRouteWithChildren,
  AppTaxaRouteRoute: AppTaxaRouteRouteWithChildren,
  AppAboutRoute: AppAboutRoute,
  AppDonateRoute: AppDonateRoute,
  AppLoginRoute: AppLoginRoute,
  AppLogoutRoute: AppLogoutRoute,
  AppSignupRoute: AppSignupRoute,
  AppIndexRoute: AppIndexRoute,
  AppKeysRoute: AppKeysRouteWithChildren,
  AppUsersUsernameRouteRoute: AppUsersUsernameRouteRouteWithChildren,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AdminUsersRouteRouteChildren {
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteRouteChildren: AdminUsersRouteRouteChildren = {
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteRouteWithChildren = AdminUsersRouteRoute._addFileChildren(
  AdminUsersRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminUsersRouteRoute: typeof AdminUsersRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminUsersRouteRoute: AdminUsersRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
